Update to r7033

diff --git a/tests/Makefile.am b/tests/Makefile.am
--- a/tests/Makefile.am
+++ b/tests/Makefile.am
@@ -32,7 +32,7 @@
 #
 ########################################################################
 
-WHIZARD_DRIVER = run_whizard.sh
+WHIZARD_UT_DRIVER = run_whizard_ut.sh
 
 UNIT_TESTS = \
     analysis.run \
@@ -153,6 +153,8 @@ UNIT_TESTS_REQ_OCAML = \
     prc_omega.run \
     compilations.run \
     compilations_static.run
+
+WHIZARD_DRIVER = run_whizard.sh
 
 TESTS_DEFAULT = \
     empty.run \
@@ -528,10 +530,11 @@ SUFFIXES = .sh .run
 	  $(SED) 's|@script@|$(top_builddir)/share/tests/$*|g' $< > $@; \
 	elif test -f $(top_srcdir)/share/tests/$*.sin; then \
 	  $(SED) 's|@script@|$(top_srcdir)/share/tests/$*|g' $< > $@; \
-	else \
-	  echo "$*.sin not found!" 1>&2; \
-	  exit 2; \
-        fi
+	fi
+#	else \
+#	  echo "$*.sin not found!" 1>&2; \
+#	  exit 2; \
+#
 	chmod +x $@
 
 structure_2.run: structure_2_inc.sin
